### ISSUE TITLE
Tyracraft website not working.

### ISSUE THREAD

**Issue by mrfiguy** [Wellinator/tyracraft#22]
The website buttons don't work, and keep directing you to the main page. I looked in console using inspect element nad theres plenty of errors. main.7916002b7fcfc523.js:1 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '-github-pages (errors listed below.)

![image_2024-02-10_155435526](https://github.com/Wellinator/tyracraft/assets/159659050/c8717bc1-2211-41ca-a3c9-87437b6009a5)

Error: Cannot match any routes. URL Segment: '-github-pages'
    at l1.noMatchError (main.7916002b7fcfc523.js:1:168517)
    at main.7916002b7fcfc523.js:1:168274
    at main.7916002b7fcfc523.js:1:139062
    at oD._error (main.7916002b7fcfc523.js:1:8117)
    at oD.error (main.7916002b7fcfc523.js:1:3021)
    at oD._error (main.7916002b7fcfc523.js:1:3260)
    at oD.error (main.7916002b7fcfc523.js:1:3021)
    at oD._error (main.7916002b7fcfc523.js:1:3260)
    at oD.error (main.7916002b7fcfc523.js:1:3021)
    at oD._error (main.7916002b7fcfc523.js:1:3260)
    at z (polyfills.f3675df6493e19dc.js:1:15999)
    at z (polyfills.f3675df6493e19dc.js:1:15534)
    at polyfills.f3675df6493e19dc.js:1:16847
    at v.invokeTask (polyfills.f3675df6493e19dc.js:1:7194)
    at Object.onInvokeTask (main.7916002b7fcfc523.js:1:76492)
    at v.invokeTask (polyfills.f3675df6493e19dc.js:1:7115)
    at M.runTask (polyfills.f3675df6493e19dc.js:1:2589)
    at _ (polyfills.f3675df6493e19dc.js:1:9209)
y_ @ main.7916002b7fcfc523.js:1
handleError @ main.7916002b7fcfc523.js:1
next @ main.7916002b7fcfc523.js:1
next @ main.7916002b7fcfc523.js:1
_next @ main.7916002b7fcfc523.js:1
next @ main.7916002b7fcfc523.js:1
(anonymous) @ main.7916002b7fcfc523.js:1
fo @ main.7916002b7fcfc523.js:1
next @ main.7916002b7fcfc523.js:1
emit @ main.7916002b7fcfc523.js:1
(anonymous) @ main.7916002b7fcfc523.js:1
invoke @ polyfills.f3675df6493e19dc.js:1
run @ polyfills.f3675df6493e19dc.js:1
runOutsideAngular @ main.7916002b7fcfc523.js:1
onHandleError @ main.7916002b7fcfc523.js:1
handleError @ polyfills.f3675df6493e19dc.js:1
runGuarded @ polyfills.f3675df6493e19dc.js:1
i.microtaskDrainDone @ polyfills.f3675df6493e19dc.js:1
_ @ polyfills.f3675df6493e19dc.js:1
Promise.then (async)
q @ polyfills.f3675df6493e19dc.js:1
R @ polyfills.f3675df6493e19dc.js:1
scheduleTask @ polyfills.f3675df6493e19dc.js:1
scheduleTask @ polyfills.f3675df6493e19dc.js:1
scheduleMicroTask @ polyfills.f3675df6493e19dc.js:1
ee @ polyfills.f3675df6493e19dc.js:1
then @ polyfills.f3675df6493e19dc.js:1
bootstrapModule @ main.7916002b7fcfc523.js:1
125 @ main.7916002b7fcfc523.js:1
n @ runtime.766b542a5b97c7ca.js:1
(anonymous) @ main.7916002b7fcfc523.js:1
a @ runtime.766b542a5b97c7ca.js:1
(anonymous) @ main.7916002b7fcfc523.js:1

**Comment by mrfiguy** [comment]
I hope it gets fixed i just got a FMCB memory card just for this

**Comment by Wellinator** [comment]
Ohh, thx for reporting! I'll fix ASAP!

**Comment by Wellinator** [comment]
@mrfiguy can you check it after last update?

**Comment by PetrusRots** [comment]
ill do so (;
